
//create user
POST http://localhost:3000/user
Content-Type: application/json 

{
    "email": "menem@gmail.com",
    "password": "rey",
    "userName" : "menem"
}
###

//login user
POST http://localhost:3000/auth/login
Content-Type: application/json 

{
    "email": "lisa@gmail.com",
    "password": "rey"
}
###

//get token
POST http://localhost:3000/auth/token
Content-Type: application/json

{
    "token":
    ""
} 
###

//get user info
GET http://localhost:3000/user
Authorization: Bearer 
###

// log out user
DELETE http://localhost:3000/auth/logout 
Content-Type: application/json

{
    "token": ""
}
###

//create project
POST http://localhost:3000/project/create
Authorization: Bearer
Content-Type: application/json

{
    "name": "bruhhh",
    "description": "testinggg"
}
###

//get project
GET http://localhost:3000/project/getp
Authorization: Bearer
Content-Type: application/json

{
    "projectId": 4
}
###

//modify project
PUT http://localhost:3000/project/modify
Authorization: Bearer
Content-Type: application/json

{
    "projectId": 4,
    "name": "modified bruuhhh",
    "description": "modified testinggg"
}
###

//delete project
DELETE http://localhost:3000/project/delete
Authorization: Bearer
Content-Type: application/json

{
    "projectId": 4
}
###