

//create user
POST http://localhost:3000/user
Content-Type: application/json 

{
    "email": "",
    "password": "rey",
    "userName" : "",
    "skillIds" : [1, 2]

}
###

//login user
POST http://localhost:3000/auth/login
Content-Type: application/json 

{
    "email": "shawty@gmail.com",
    "password": "rey"

}
###

//get token
POST http://localhost:3000/auth/token
Content-Type: application/json

{
    "token":
    ""
} 
###

//get user info
GET http://localhost:3000/user
Authorization: Bearer 
###

// log out user
DELETE http://localhost:3000/auth/logout 
Content-Type: application/json

{
    "token": ""
}
###

//create project
POST http://localhost:3000/project/create
Authorization: Bearer
Content-Type: application/json

{
    "name": "dog",
    "description": "red"
}
###

//get project
GET http://localhost:3000/project/getp
Authorization: Bearer
Content-Type: application/json

{
    "projectId": 2
}
###

//modify project
PUT http://localhost:3000/project/modify
Authorization: Bearer
Content-Type: application/json

{
    "projectId": 4,
    "name": "modified bruuhhh",
    "description": "modified testinggg"
}
###

//delete project
DELETE http://localhost:3000/project/delete
Authorization: Bearer
Content-Type: application/json

{
    "projectId": 4
}
###

POST http://localhost:3000/signup
Authorization: Bearer
Content-Type: application/json

{
    "username": "pp",
    "email": "pp@gmail.com",
    "password": "pp",
    "selectedOptions": ["opcion1"]
}

###

//search project

GET http://localhost:3000/search/searchProject
Authorization: Bearer
Content-Type: application/json

{
    "searchString": "siii"
}


###

