//request user searchHistory
GET http://localhost:3000/userData/searchHistory
Authorization: Bearer
Content-Type: application/json

{
    "userId" : "2"
}

###

GET http://localhost:3000/userData/visitHistory
Authorization: Bearer
Content-Type: application/json

{
    "userId" : "2"
}
