POST http://localhost:3000/userInteractions/sendCollaborationRequest/10
Content-Type: application/json
Authorization: Bearer <token>

{
    "message": "I would like to collaborate on this project"
}


### 


GET http://localhost:3000/userInteractions/getOwnCollaborationRequests
Content-Type: application/json
Authorization: Bearer <token>

###

GET http://localhost:3000/userInteractions/getOwnCollaborationRequest/42
Content-Type: application/json
Authorization: Bearer <token>

###

GET http://localhost:3000/userInteractions/getCollaborationRequests
Content-Type: application/json
Authorization: Bearer <token>


###

GET http://localhost:3000/userInteractions/getCollaborationRequest/19
Content-Type: application/json
Authorization: Bearer <token>


###

POST http://localhost:3000/userInteractions/acceptCollaborationRequest/19
Content-Type: application/json
Authorization: Bearer <token>

{
    "response": "I accept your collaboration request"
}

###

POST http://localhost:3000/userInteractions/rejectCollaborationRequest/21
Content-Type: application/json
Authorization: Bearer <token>

{
    "response": "I reject your collaboration request"
}

###

DELETE http://localhost:3000/userInteractions/deleteCollaborationRequest/10
Content-Type: application/json
Authorization: Bearer <token>

###


POST http://localhost:3000/userInteractions/like/41
Authorization: Bearer
Content-Type: application/json


###

GET http://localhost:3000/userInteractions/getLiked
Authorization: Bearer
Content-Type: application/json

###

DELETE http://localhost:3000/userInteractions/deleteAllLikes
Authorization: Bearer
Content-Type: application/json

###

DELETE http://localhost:3000/userInteractions/deleteAllCollaborationRequests
Authorization: Bearer
Content-Type: application/json

###